// src/components/widget/DisplaySettings.svelte
<script lang="ts">
  import { getDefaultHue, getHue, setHue } from "../../utils/setting-utils";

  let hue = getHue();
  const defaultHue = getDefaultHue();
  type I18nWindow = Window & { i18nResources?: Record<string, string> };

  const t = (key: string, fallback: string): string => {
    const value = typeof window !== "undefined"
      ? (window as I18nWindow).i18nResources?.[key]
      : undefined;
    return value && !value.includes("#{") ? value : fallback;
  };

  function resetHue() {
    hue = getDefaultHue();
  }

  $: if (hue || hue === 0) {
    setHue(hue);
  }
</script>

<div id="display-setting" class="float-panel float-panel-closed absolute transition-all w-80 right-4 px-4 py-4">
  <div class="flex flex-row gap-2 mb-3 items-center justify-between">
    <div class="flex gap-2 font-bold text-lg text-neutral-900 dark:text-neutral-100 transition relative ml-3
            before:w-1 before:h-4 before:rounded-md before:bg-(--primary)
            before:absolute before:-left-3 before:top-[0.33rem]"
    >
      {t("theme.color", "主题色")}
      <button aria-label={t("theme.resetDefault", "Reset to Default")} class="btn-regular w-7 h-7 rounded-md  active:scale-90 will-change-transform"
              class:opacity-0={hue === defaultHue} class:pointer-events-none={hue === defaultHue} on:click={resetHue}>
        <div class="text-(--btn-content)">
          <div icon="fa6-solid:arrow-rotate-left" class="icon-[fa6-solid--arrow-rotate-left] text-[0.875rem]"></div>
        </div>
      </button>
    </div>
    <div class="flex gap-1">
      <div id="hueValue" class="transition bg-(--btn-regular-bg) w-10 h-7 rounded-md flex justify-center
            font-bold text-sm items-center text-(--btn-content)">
        {hue}
      </div>
    </div>
  </div>
  <div class="w-full h-6 px-1 bg-[oklch(0.80_0.10_0)] dark:bg-[oklch(0.70_0.10_0)] rounded select-none">
    <input aria-label="11" type="range" min="0" max="360" bind:value={hue}
           class="slider" id="colorSlider" step="5" style="width: 100%">
  </div>
</div>


<style lang="stylus">
  #display-setting
    input[type="range"]
      -webkit-appearance none
      height 1.5rem
      background-image var(--color-selection-bar)
      transition background-image 0.15s ease-in-out

      /* Input Thumb */
      &::-webkit-slider-thumb
        -webkit-appearance none
        height 1rem
        width 0.5rem
        border-radius 0.125rem
        background rgba(255, 255, 255, 0.7)
        box-shadow none
        &:hover
          background rgba(255, 255, 255, 0.8)
        &:active
          background rgba(255, 255, 255, 0.6)

      &::-moz-range-thumb
        -webkit-appearance none
        height 1rem
        width 0.5rem
        border-radius 0.125rem
        border-width 0
        background rgba(255, 255, 255, 0.7)
        box-shadow none
        &:hover
          background rgba(255, 255, 255, 0.8)
        &:active
          background rgba(255, 255, 255, 0.6)

      &::-ms-thumb
        -webkit-appearance none
        height 1rem
        width 0.5rem
        border-radius 0.125rem
        background rgba(255, 255, 255, 0.7)
        box-shadow none
        &:hover
          background rgba(255, 255, 255, 0.8)
        &:active
          background rgba(255, 255, 255, 0.6)

</style>

// src/preact/components/DisplaySettings.tsx
import "../../styles/display-settings.styl";
import { useEffect, useState } from "preact/hooks";
import { getDefaultHue, getHue, setHue as setShue } from "../../utils/setting-utils";

export function DisplaySettings() {
  const [hue, setHue] = useState(getHue());

  const defaultHue = getDefaultHue();

  function resetHue() {
    setHue(defaultHue);
  }
  // 监听 hue 的变化
  useEffect(() => {
    setShue(hue);
  }, [hue]);
  return (
    <>
      <div className="mb-3 flex flex-row items-center justify-between gap-2">
        <div className="relative ml-3 flex gap-2 text-lg font-bold text-neutral-900 transition before:absolute before:top-[0.33rem] before:-left-3 before:h-4 before:w-1 before:rounded-md before:bg-[var(--primary)] dark:text-neutral-100">
          Theme Color
          <button
            aria-label="Reset to Default"
            className={`btn-regular flex h-7 w-7 items-center justify-center rounded-md transition active:scale-90 ${
              hue === defaultHue ? "pointer-events-none opacity-0" : ""
            }`}
            onClick={resetHue}
          >
            <div className="flex items-center justify-center text-[var(--btn-content)]">
              <span className="icon-[material-symbols--device-reset] text-[1.3rem]"></span>
            </div>
          </button>
        </div>
        <div className="flex gap-1">
          <div
            id="hueValue"
            className="flex h-7 w-10 items-center justify-center rounded-md bg-[var(--btn-regular-bg)] text-sm font-bold text-[var(--btn-content)] transition"
          >
            {hue}
          </div>
        </div>
      </div>
      <div className="h-6 w-full rounded bg-[oklch(0.80_0.10_0)] px-1 select-none dark:bg-[oklch(0.70_0.10_0)]">
        <input
          aria-label="Color Picker"
          type="range"
          min="0"
          max="360"
          value={hue}
          onInput={(e) => setHue(Number((e.target as HTMLInputElement).value))}
          className="slider"
          id="colorSlider"
          step="5"
          style="width: 100%"
        />
      </div>
    </>
  );
}
